version: "3.8"
services:
  nginx:
    ports:
      - "8080:80"
  
  go-app:
    build:
      context: ./backend
      args:
        - NGINX_PORT=8080
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=kittens-are-cute
      - NGINX_PORT=8080
      - DB_USERNAME=root
      - DB_PASSWORD=mypassword
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=mydb
      - ADMIN_ORG_NAME=Admin
      - ADMIN_ORG_HEAD=Rohit-1
      - ADMIN_USERNAME=Rohit-1
      - ADMIN_PASSWORD=pass-1
    command: ["go", "run", "cmd/main.go"]

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=mydb